version: '3'
services:

  gitea_postgres:
    image: postgres:14
    container_name: gitea_postgres
    restart: always
    networks:
      - internal
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD={{ git__postgres_password }}
      - POSTGRES_DB=gitea
    volumes:
      - "{{ docker_mounts_directory }}/git/postgresql:/var/lib/postgresql/data"

  gitea_postgres_backups:
    restart: always
    image: prodrigestivill/postgres-backup-local:14-alpine
    container_name: gitea_postgres_backups
    networks:
      - internal
    depends_on:
      - gitea_postgres
    environment:
      - POSTGRES_HOST=gitea_postgres
      - POSTGRES_DB=gitea
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD={{ git__postgres_password }}
      - POSTGRES_EXTRA_OPTS=--format c # So we can use pg_restore to restore the database
      - TZ=Europe/Brussels
      - HEALTHCHECK_ID={{ git__postgres_backups_healthcheck_id }}
    volumes:
      - /mnt/storage/backups/gitea:/backups
      - ./hooks:/hooks

  gitea:
    image: gitea/gitea:1.17
    container_name: gitea
    restart: always
    networks:
      - internal
      - web
    depends_on:
      - gitea_postgres
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.gitea.entryPoints=websecure
      - traefik.http.routers.gitea.rule=Host(`git.{{ ansible_fqdn }}`)
      - traefik.http.routers.gitea.service=gitea
      - traefik.http.services.gitea.loadBalancer.server.port=3000
    environment:
      - USER_UID={{ git_user_creation_result.uid }}
      - USER_GID={{ git_user_creation_result.group }}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD={{ git__postgres_password }}
      - ROOT_URL=https://git.{{ ansible_fqdn }}/
      - GITEA__indexer__ISSUE_INDEXER_TYPE=db # Fix for running under mergerfs

      - GITEA__security__INSTALL_LOCK=true # Disables install page
      - GITEA__security__SECRET_KEY={{ git__gitea__secret_key }}
      - GITEA__security__INTERNAL_TOKEN={{ git__gitea__internal_secret }}
      - GITEA__security__PASSWORD_CHECK_PWN=true
      - GITEA__security__MIN_PASSWORD_LENGTH=8

      - GITEA__webhook__ALLOWED_HOST_LIST=*
      - GITEA__service__REGISTER_MANUAL_CONFIRM=true

      - GITEA__server__LANDING_PAGE=explore
      - GITEA__server__SSH_DOMAIN=git.{{ ansible_fqdn }}

      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__FROM={{ smtp__from }}
      - GITEA__mailer__MAILER_TYPE=smtp
      - GITEA__mailer__HOST={{ smtp__host }}:{{ smtp__port }}
      # 2 below will be used instead as above frome 1.18, so I have put them here for future proofing
      - GITEA__mailer__SMTP_ADDR={{ smtp__host }}
      - GITEA__mailer__SMTP_PORT={{ smtp__port }}
      - GITEA__mailer__IS_TLS_ENABLED=false # I've tried everything and no matter that I use port 465 with TLS enabled it just doesn't want to send mail if I let this on...
      - GITEA__mailer__USER={{ smtp__user }}
      - GITEA__mailer__PASSWD={{ smtp__pass | replace('$', '$$') }}
    volumes:
      - /home/git/.ssh/:/data/git/.ssh # For SSH passthrough
      - /mnt/storage/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:2222:22"

networks:
  web:
    external: true
  internal:
